spring:
  application:
    name: avaliacao-mirante
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./target/h2db/db/database;DB_CLOSE_DELAY=1;AUTO_SERVER=TRUE;
    username: amanda
    password:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  swagger:
    title: Avaliação Mirante
    version: 1.0.0

server:
  port: 8080